### PR TITLE
Update README.md with resolve documentation

### PR DESCRIPTION
**Pull request by JesseFarebro**
One thing I was looking for with PostCSS and [postcss-import] was the ability to hook into my alias when importing css modules.
After searching for a little I found a pretty elegant solution that may be worth documenting.

Let me know if you need any further changes.

### CODE REVIEW

**Comment by ai** [comment]
Webpack config are hell 😟. Code snippets become as spattered program. Maybe for this case you should release some small npm module to keep config readable?

**Comment by MoOx** [comment]
Or even include this in this module?

**Comment by ai** [comment]
@MoOx yeap, like `postcssImport.webpack`. Do I need to create issue in `postcss-import`?

/cc @TrySound

**Comment by MoOx** [comment]
maybe @JesseFarebro can do a pull request over there directly by inspiring himself from the addDependencyTo ?

**Comment by JesseFarebro** [comment]
@ai I couldn't agree more with you!

@MoOx I'll shoot a PR there way and see how they feel. If not this should be gist worthy, it's a pretty elegant solution considering all things.

**Comment by ai** [comment]
@JesseFarebro please send other PR when you add `postcssImport.webpack`

**Pull request closed without merging**
