### PR TITLE
New PR that meets the convention. 

### PR DESCRIPTION
**Pull request by sainthkh**
In the previous code, PRed code didn't meet the convention. So, I fixed it here. 

**For the readers who googled this document.**

We discussed about the configuration path for the postcss-loader at #143. If you want to know how it works, read that document.

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@sainthkh did you test it with webpack >= v2.x 

```js
{
  test: /\.css/,
  use: [ 
    { loader: 'css-loader', options: { importLoaders: 1 } }, 
    { loader: 'postcss-loader', options: { config: 'alternative/path/to/postcss.config.js' } }
  ]
}
```

Normally should be working just fine as it is implemented atm

**Comment by sainthkh** [comment]
@michael-ciniawsky I've checked it out and there was no problem.

**Comment by michael-ciniawsky** [comment]
@sainthkh This has popped in my mind recently, but I can also add it later :) 

**webpack.config.js**
```js
{
  test: /\.css/,
  use: [ 
    { loader: 'css-loader', options: { importLoaders: 1 } }, 
    { 
       loader: 'postcss-loader', 
       options: { 
         config: { file: 'alternative/path/to/postcss.config.js', ctx: { modules: true } } 
       }
  ]
}
```

**postcss.config.js**
```js
module.exports = (ctx) => {
   return {
    parser: 'sugarss',
    plugins: {
      'postcss-import': {},
      'postcss-modules': ctx.modules ? {} : false
    }
  }
}
```

@ai Please confirm PR

**Comment by ai** [comment]
I will confirm and release today at evening

**Comment by ai** [comment]
Published in 1.2. Thanks for your work =^_^=.

**Pull request merged**
