### PR TITLE
Fix file extension typo in Syntaxes section.

### PR DESCRIPTION
**Pull request by josephdburdick**
Hi all, found this typo, let me know if you have any questions.

### CODE REVIEW

**Comment by ai** [comment]
`.sss` is a SugarSS

**Comment by ai** [comment]
:D You are not first who send this PR. Maybe we should find better example.

**Comment by michael-ciniawsky** [comment]
@ai I add a comment that `.sss` === SugarSS in the new docs, taking it into account, I push them tomorrow when I finally have some spare time for OSS

**Pull request closed without merging**
