### PR TITLE
Upgrade postcss-load-config to 2.1.0

### PR DESCRIPTION
**Pull request by akshayas**
#### `Commit Message Summary (CHANGELOG)`

```bash
Upgrade postcss-load-config to 2.1.0
```

### Type

> ℹ️ What type of changes does your code introduce?

- [x] Chore

### Issues
`js-yaml` needed to be upgraded to atleast 3.13.1 since it contains a patch for a high severity vulnerability which was flagged by dependabot/github alerts. Details are mentioned below

```
WS-2019-0063 More information
high severity
Vulnerable versions: < 3.13.1
Patched version: 3.13.1
Js-yaml prior to 3.13.1 are vulnerable to Code Injection. The load() function may execute arbitrary code injected through a malicious YAML file.
```
> ℹ️ What issue(s) (if any) are closed by your PR?

N/A

### SemVer

> ℹ️  What changes to the current `semver` range does your PR introduce?

- [x] Fix (:label: Patch)

### Checklist

> ℹ️  You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is a reminder of what we are going to look for before merging your code.

- [ ] Lint and unit tests pass with my changes
- [ ] I have added tests that prove my fix is effective/works (if needed)
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes are merged and published in downstream modules

### CODE REVIEW

**Comment by akshayas** [comment]
Tests on master appear to be broken. Same build failures as the 2 most recent builds

[PR408](https://travis-ci.org/postcss/postcss-loader/builds/516618215)
[PR415](https://travis-ci.org/postcss/postcss-loader/builds/576468419)

**Comment by evilebottnawi** [comment]
Just update own lock file, no need do PR

**Comment by akshayas** [comment]
> Just update own lock file, no need do PR

I have already done that but its less than ideal so fixing the root of the issue. Besides this benefits everyone.

**Comment by evilebottnawi** [comment]
@akshayas please read how semver works, new installation always provide latest version

**Pull request closed without merging**
