### PR TITLE
Add support for postcss-js

### PR DESCRIPTION
**Pull request by SimonDegraeve**

### CODE REVIEW

**Comment by ai** [comment]
Awesome! But can you aslo provide some test for this case? You can look to other test as a sample.

**Comment by SimonDegraeve** [comment]
Done and rebased ;-)

**Comment by ai** [comment]
Sorry, that I add more and more sub tasks :). But it is really awesome feature :).

Can you asl add some docs (my English is bad) about it. I think many users can miss this awesome way to use PostCSS.

**Comment by SimonDegraeve** [comment]
Done.

> (my English is bad)

Well, I am French, so mine too...

**Comment by ai** [comment]
:D

**Comment by SimonDegraeve** [comment]
For the record, I am using `postcss-js` because I am working on an implementation of [material design](https://www.google.com/design/spec/material-design/introduction.html) with [React](https://github.com/facebook/react).

I am not a big fan of inline styles and all their cons (media-query, pseudo-element, prefix, etc). Of course many [modules](https://github.com/MicheleBertoli/css-in-js) solve them (or try to) but the performance are not good enough for me (and my company). Check [Material UI](http://material-ui.com/) on mobile...

And for theming, I have been trying to achieve my goal with [css-modules-values](https://github.com/css-modules/postcss-modules-values), [postcss-functions](https://github.com/andyjansson/postcss-functions), [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars), etc... but none was a good fit.

So after weeks of trying different approach, I think having all power of JS with `postcss-js` and then `css-modules` for composability and pattern is a real win.

**Comment by ai** [comment]
Yeap. There was [Styling](https://github.com/andreypopp/styling) project. But seems like it doesn’t need anymore.

**Comment by SimonDegraeve** [comment]
Indeed, I am glad I finally found my dream stack.

**Comment by ai** [comment]
I will release version right after move project to AVA

**Comment by SimonDegraeve** [comment]
Actually I just realised that in the readme the reference to `postcssImport` in the `postcss-js` example is useless. Damn copy/paste.

**Comment by ai** [comment]
fixed :)

**Comment by ai** [comment]
Released in 0.8

**Pull request merged**
