### PR TITLE
Feature/postcss option as function

### PR DESCRIPTION
**Pull request by cybercase**
Hello @ai 

This PR helps to address the issue #8 . A full example is provided in README.
Let me know what you think. Thanks

Stefano

### CODE REVIEW

**Comment by ai** [comment]
Awesome.

Maybe we need to use function by default?

Can you send a PR with default function and special section with `onImport` example?

**Comment by cybercase** [comment]
Thanks for merging!
Of course I can send another PR

Are the following changes ok?
- Update of "Usage" and "Plugins Pack" sections to use function instead of Objects or Array.
- Update of "Plugin Function" section with an "Integration with postcss-import"

**Comment by ai** [comment]
Yeap :)

**Comment by ai** [comment]
@cybercase I am waiting for second PR to make a release :)

**Pull request merged**
